// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../src/components/Application/AppProvider.vue')['default']
    Link: typeof import('./../src/components/Basic/Link.vue')['default']
    Markdown: typeof import('./../src/components/Markdown/Markdown.vue')['default']
    MyCode: typeof import('./../src/components/Markdown/MyCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/Icon/src/SvgIcon.vue')['default']
  }
}
